from __future__ import annotations

from app.repositories.schemas import CategorySqlSpec

# 七张 POI 逻辑表名。Collector 层和 DAG 配置都使用这组常量，避免字符串散落。
POI_ATTRACTION = "poi_attraction"
POI_SHOPPING = "poi_shopping"
POI_ACTIVITY = "poi_activity"
POI_RESTAURANT = "poi_restaurant"
POI_FITNESS = "poi_fitness"
POI_ENTERTAINMENT = "poi_entertainment"
POI_BEAUTY = "poi_beauty"

# fmt: off
POI_CATEGORIES = (
    POI_ATTRACTION, POI_SHOPPING, POI_ACTIVITY, POI_RESTAURANT,
    POI_FITNESS, POI_ENTERTAINMENT, POI_BEAUTY
)
# fmt: on

CATEGORY_SQL_SPECS: dict[str, CategorySqlSpec] = {
    POI_RESTAURANT: CategorySqlSpec(
        table="poi_restaurant",
        id_expr="source_id",
        name_expr="name",
        category=POI_RESTAURANT,
        subcategory_expr="COALESCE(NULLIF(biz_category, ''), 'restaurant')",
        lat_expr="lat",
        lon_expr="lng",
        address_expr="address",
        rating_expr="rating",
        price_expr="cost",
        open_expr="open_time",
        tag_expr="CONCAT_WS(' ', cuisine_tag, keytag, type, query_label)",
        image_expr="head_image",
        images_expr="photos",
        base_where="name <> '' AND lat IS NOT NULL AND lng IS NOT NULL",
        order_expr="COALESCE(favorite_num, 0) DESC",
        filter_fields=(
            "name",
            "biz_category",
            "cuisine_tag",
            "keytag",
            "type",
            "query_label",
            "city",
            "district",
            "business_area",
            "lat",
            "lng",
            "rating",
            "cost",
            "open_time",
            "favorite_num",
        ),
        tag_fields=("cuisine_tag", "keytag", "type", "query_label"),
    ),
    POI_ACTIVITY: CategorySqlSpec(
        table="poi_activities",
        id_expr="CAST(activity_id AS CHAR)",
        name_expr="title",
        category=POI_ACTIVITY,
        subcategory_expr="'activity'",
        lat_expr="CAST(SUBSTRING_INDEX(location, ',', 1) AS DECIMAL(10, 6))",
        lon_expr="CAST(SUBSTRING_INDEX(location, ',', -1) AS DECIMAL(10, 6))",
        address_expr="address_desc",
        rating_expr=None,
        price_expr="price",
        open_expr="available_date",
        tag_expr="CONCAT_WS(' ', subtitle, CAST(category_info AS CHAR))",
        image_expr="NULL",
        images_expr="images",
        base_where=(
            "title <> '' AND location IS NOT NULL AND location <> '' AND INSTR(location, ',') > 0"
        ),
        order_expr="updated_time DESC",
        filter_fields=(
            "title",
            "subtitle",
            "category_info",
            "city_id",
            "category_id",
            "sub_category_id",
            "leaf_category_id",
            "location",
            "price",
            "available_date",
            "updated_time",
        ),
        tag_fields=("subtitle",),
    ),
    POI_ATTRACTION: CategorySqlSpec(
        table="poi_attractions",
        id_expr="CAST(id AS CHAR)",
        name_expr="name",
        category=POI_ATTRACTION,
        subcategory_expr="'attraction'",
        lat_expr="lat",
        lon_expr="lng",
        address_expr="address",
        rating_expr="score",
        price_expr=None,
        open_expr="JSON_EXTRACT(open_time, '$')",
        tag_expr="tags",
        image_expr="head_image",
        images_expr="NULL",
        base_where="name <> '' AND lat IS NOT NULL AND lng IS NOT NULL",
        order_expr="COALESCE(hot_score, 0) DESC",
        filter_fields=(
            "name",
            "name_en",
            "alias",
            "tags",
            "dest_id",
            "lat",
            "lng",
            "score",
            "comment_score",
            "open_time",
            "suggested_duration",
            "hot_score",
        ),
        tag_fields=("tags",),
    ),
    POI_SHOPPING: CategorySqlSpec(
        table="poi_shoppings",
        id_expr="source_id",
        name_expr="name",
        category=POI_SHOPPING,
        subcategory_expr="COALESCE(NULLIF(categories, ''), 'shopping')",
        lat_expr="lat",
        lon_expr="lng",
        address_expr="address",
        rating_expr="comment_score",
        price_expr=None,
        open_expr="open_time_tips",
        tag_expr="CONCAT_WS(' ', tags, categories)",
        image_expr="head_image",
        images_expr="images",
        base_where="name <> '' AND lat IS NOT NULL AND lng IS NOT NULL",
        order_expr="COALESCE(comment_num, 0) DESC",
        filter_fields=(
            "name",
            "name_local",
            "name_en",
            "brand_name_cn",
            "tags",
            "categories",
            "lat",
            "lng",
            "comment_score",
            "open_time_tips",
            "comment_num",
        ),
        tag_fields=("tags", "categories"),
    ),
    POI_FITNESS: CategorySqlSpec(
        table="poi_fitness",
        id_expr="source_id",
        name_expr="name",
        category=POI_FITNESS,
        subcategory_expr="COALESCE(NULLIF(fitness_tag, ''), 'fitness')",
        lat_expr="lat",
        lon_expr="lng",
        address_expr="address",
        rating_expr="rating",
        price_expr="cost",
        open_expr="open_time",
        tag_expr="CONCAT_WS(' ', fitness_tag, keytag, type, query_label)",
        image_expr="head_image",
        images_expr="photos",
        base_where="name <> '' AND lat IS NOT NULL AND lng IS NOT NULL",
        order_expr="COALESCE(favorite_num, 0) DESC",
        filter_fields=(
            "name",
            "biz_category",
            "fitness_tag",
            "keytag",
            "type",
            "query_label",
            "city",
            "district",
            "business_area",
            "lat",
            "lng",
            "rating",
            "cost",
            "open_time",
            "favorite_num",
        ),
        tag_fields=("fitness_tag", "keytag", "type", "query_label"),
    ),
    POI_ENTERTAINMENT: CategorySqlSpec(
        table="poi_entertainment",
        id_expr="source_id",
        name_expr="name",
        category=POI_ENTERTAINMENT,
        subcategory_expr="COALESCE(NULLIF(entertainment_type, ''), 'entertainment')",
        lat_expr="lat",
        lon_expr="lng",
        address_expr="address",
        rating_expr="rating",
        price_expr="cost",
        open_expr="open_time",
        tag_expr="CONCAT_WS(' ', entertainment_type, keytag, type, query_label)",
        image_expr="head_image",
        images_expr="photos",
        base_where="name <> '' AND lat IS NOT NULL AND lng IS NOT NULL",
        order_expr="COALESCE(groupbuy_num, 0) DESC",
        filter_fields=(
            "name",
            "biz_category",
            "entertainment_type",
            "keytag",
            "type",
            "query_label",
            "city",
            "district",
            "business_area",
            "lat",
            "lng",
            "rating",
            "cost",
            "open_time",
            "groupbuy_num",
        ),
        tag_fields=("entertainment_type", "keytag", "type", "query_label"),
    ),
    POI_BEAUTY: CategorySqlSpec(
        table="poi_beauty",
        id_expr="source_id",
        name_expr="name",
        category=POI_BEAUTY,
        subcategory_expr="COALESCE(NULLIF(beauty_type, ''), 'beauty')",
        lat_expr="lat",
        lon_expr="lng",
        address_expr="address",
        rating_expr="rating",
        price_expr="cost",
        open_expr="open_time",
        tag_expr=(
            "CONCAT_WS(' ', service_tag, beauty_type, query_keywords, keytag, type, query_label)"
        ),
        image_expr="head_image",
        images_expr="photos",
        base_where="name <> '' AND lat IS NOT NULL AND lng IS NOT NULL",
        order_expr="COALESCE(favorite_num, 0) DESC",
        filter_fields=(
            "name",
            "biz_category",
            "service_tag",
            "beauty_type",
            "query_keywords",
            "keytag",
            "type",
            "query_label",
            "city",
            "district",
            "business_area",
            "lat",
            "lng",
            "rating",
            "cost",
            "open_time",
            "favorite_num",
        ),
        tag_fields=(
            "service_tag",
            "beauty_type",
            "query_keywords",
            "keytag",
            "type",
            "query_label",
        ),
    ),
}

NAME_SEARCH_LIMIT = 10
RATING_FALLBACKS: tuple[float | None, ...] = (4.2, 4.0, 3.8, None)
BUDGET_FALLBACK_MULTIPLIERS: tuple[float | None, ...] = (1.0, 1.25, 1.6, None)
RADIUS_FALLBACK_MULTIPLIERS: tuple[float, ...] = (1.0, 1.4, 2.0, 2.6)
SEARCH_COLLATION = "utf8mb4_unicode_ci"
